### ISSUE TITLE
Progress Tracker:  Malakula Data:  Culture Lists

### ISSUE THREAD

**Issue by DarjaAppelganz** [sndcomp/website#472]
This issue is only for the Culture Lists, and should be kept separate from the other Malakula Tracker Issue #474, for the main, original Basic Vocabulary 215-item list.

- [ ] This new issue should replace the previous Malakula culture list tracker issue: #460.  That should be checked over to see if anything in it is left outstanding.  If so, those outstanding points should be merged into this issue, and the old issue #460 should be closed (closed, DDA). 

----
## New Recordings to Segment and Upload:  Culture Lists
- [x] wl_1630127-R_Burmbar_Fartavo_revised_selected
- [x] wl_1630140_Uripiv_TautuVillage_selected
- [x] wlc_1620037_Pangkumu_Datisman_selected
- [x] wlc_1620034-R_Tirax_Mae_revised_selected
- [x] wlc_1630064_Siviti_Gonwar_selected
- [x] wlc_1630065_Malua Bay_Petarmul_selected
- [x] wlc_1630066_Espiegel_s_Bay_selected
- [x] wlc_1630068_Najit_Tanmial_selected
- [x] wlc_1620038_Unua_Unua3_selected
- [x] wlc_1620044_Mbwenelang_selected
- [x] wlc_1620046_Siviti (FIRST SET)
- [x] wlc_1620051_Atchin_Mainland_selected
- [x] wlc_1620034_Tirax_02_Mae_selected
- [x] wlc_1630097_Uripiv_Tautu_selected
- [x] wlc_1630096_Avok_Hokai_selected
- [x] wlc_1630094_Vao_Small Island_selected
- [x] wlc_1630084_Nasvang_selected
- [x] wlc_1630083_Axamb_selected
- [x] wlc_1630082 Aulua Asorokh_selected
- [x] wlc_1630081_Nisvai (Mandri)_Blacksands_selected
- [x] wlc_1630080_Mburmbar_Fartavo_selected
- [ ] wlc_1630075 Tasmbol Usus_selected
- [ ] wlc_1630072_Wala_Worprev_selected_2
- [ ] wlc_1630072_Wala_Worprev_selected
- [ ] wlc_1630071_SC_Atchin_SmallIsland_selected
- [ ] wlc_1630067_Nese_selected
- [ ] wlc_1630063_Neverver_Limap_selected
- [ ] wlc_1630061_Fifti_Malmbor_selected
- [ ] wlc_1630060_Neverver_Mindu_selected
- [ ] wlc_1630058_Avava_Khatbol_selected
- [ ] wlc_1630056_Naman_Lendo_selected
- [ ] wlc_1630055_Neve'ei_Vinmavis_selected (without kin terms)
- [x] wlc_1620048_Wowo_Alavas_Wowo_selected
- [x] wlc_1620047_Batarxopu (SECOND SET)
- [ ] wlc_0001_Naati_01_selected

**Comment by AvivaShimelman** [comment]
Hi folks!

Glad to see you're back at work on these. I had thought that the project was being abandoned. It looks like you're taking the "less likely to be edited" first, which is good. I'll move the "could still be edited"s into that file (the issue was not with the sound, but with a couple of items I was thinking of killing because I wasn't sure I had equivalent referents). I'll just move those in.

VERY IMPORTANT! What version of the transcripts are you using? The last one I posted was dated 2017 06 22. 

Which leads me to a general issue: Please keep me in the loop. As this list was idiosyncratic from the beginning and changes were made along the way, any assumptions could mean a lot of back-tracking later on.
Hope all are well.

A.

**Comment by AvivaShimelman** [comment]
Be aware that files labeled "SC" supplement files from the same language/dialect. The issue arose because I did two rounds of recordings. In those cases where the recordings are from the same speaker (check the metadata), these recordings can be merged. In those cases where there are different speakers, it's a judgement call whether to merge or keep independent. There are no item overlaps. An "SC" recording is always the most recent and I cut any "doubles" from the earlier recording. 
A.
