### ISSUE TITLE
Progress Tracker: Pentecost

### ISSUE THREAD

**Issue by DarjaAppelganz** [sndcomp/website#482]

**Comment by DarjaAppelganz** [comment]
----
## New Recordings to Segment and Upload:  Pentecost 
- [] Oce_Van_Pent_South_Sa_F_Rangusuksu_Dl/Sa_F_Yantas-Rangusuksu-BVFull. renamed, 
- [] Oce_Van_Pent_South_Sa_F_Yangtus_Dl/Sa_F-Yangtus-Rangusuksu-Pentecost-BVFull. marked, renamed, extr
- [] Oce_Van_Pent_South_Sa_Ranwas_Dl/Sa_Rawas-Ehe-Pentecost-BVFull. renamed,
- [] Oce_Van_Pent_South_Sa_General_Dl/Sa_Sa General-Poantu-Pentecost-BVFull. marked, renamed, extr
- [] Oce_Van_Pent_South_Sa_Bunlap_Dl/Sa-Bunlap-Baie Homo-Pentecost-BVFull. marked, renamed, extr
- [] Oce_Van_Pent_South_Sa_Haa_Dl/Sa-Ha-Londar-Pentecost-BVFull. marked, renamed, extr
- [] Oce_Van_Pent_South_Sa_Paangi_Dl/Sa-Panngi-Baie Homo-Pentecost-BVFull. marked, renamed, extr
- [] Oce_Van_Pent_South_Sa_F_Ponof_Dl/Sa-Sa F-Ponof-Pentecost-BVFull. marked, renamed, extr
- [] 
- [] 
- []
