### ISSUE TITLE
Progress Tracker:  Vanuatu Other Islands (not Malakula)

### ISSUE THREAD

**Issue by PaulHeggarty** [sndcomp/website#485]
2019 04 10  

### Pentecost:  Sa Dialects
- [x] These should all now be on the website and correctly named, waiting for the recordings to be uploaded.
- [x] @DarjaAppelganz has been working through these to mark them up herself.  To be completed:  see #482.
- [x] Transcriptions should already be completed, and the transcriptions file is to be supplied by @maryewal.

### Pentecost:  Lokasai & Raga
These are effectively 'legacy' recordings, not done to Sound Comparisons procedures, and will need a *lot* of painstaking manual correction.  There are no master sound files, but pre-cut word by word files.
- [ ] The word by word sound files are not named to the Sound Comparisons system, but idiosyncratically and differently in Lokasai & Raga.  All need to be individually renamed.
- [ ] The word by word sound files are stereo, but do seem to have different tracks, so maybe should be kept as stereo.
- [ ] The word by word sound files have a lot of background noise, but there is little that can be done now.  They do need to be faded in and out, however, preferably by one of the Sound Comparisons scripts to do this.
- [ ] The word by word sound files include multiple pronunciations of the same word.  Only one needs to be selected in each case, again this will have to be done manually.
- [ ] The Language Reference Data Sheet (Excel) needs to be provided by @maryewal.
- [ ] On the basis of that sheet, @PaulHeggarty and @maryewal will need to then create the corresponding language variety names in the Sound Comparisons database.

### Maewo & Ambae
- [ ] The Language Reference Data Sheet (Excel) needs to be provided by @maryewal.
- [ ] On the basis of that sheet, @PaulHeggarty and @maryewal will need to then create the corresponding language variety names in the Sound Comparisons database.
- [ ] The master sound files are unclearly named, and need to be renamed.
- [ ] **TASK 1**:  The master sound files are in stereo, and need to be converted to mono.
- [ ] The corresponding TextGrids only have a single tier, not appropriately named.  It will have to be renamed, and the script run to add the usual Sound Comparisons tiers.
- [ ] The master sound files are marked up with corresponding TextGrids, but with the sequence number only, 1 to 215.  This will need to be converted to the English and/or Bislama equivalents, although preferably separately, in the correct Sound Comparisons tier (with the multiple indications of 1 to 215 retained in the original tier).  This will require a new ad hoc praat script.
- [ ] The TextGrids are marked up with multiple (usually three) pronunciations of the same word.  Only one needs to be selected in each chase.  This is best done on the English or Bislama tier, however, deleting the entries for the (usually two) pronunciations that are not to be retained.
- [ ] The TextGrid sound segmentations are not always very accurate, and will have to be manually improved.

**Comment by DarjaAppelganz** [comment]
Sa dialects are all marked up and uploaded (except Raga and Lokasaí) --> issue 482 closed

**Comment by maryewal** [comment]
Sa:
Transcriptions were submitted in March 2019. 

"Other" Pentecost:
Lana has been given a contract extension to document the central Pentecost languages over the next months. If that goes quickly enough, I could ask her to also make a visit exclusively to work on Raga too. This may be better overall. So, for now, **let's hold on further processing of Raga**.

Maewo & Ambae:
When I last checked with Iveth in July, she had finished these tasks. I thought she had forwarded them to Darja already. I'll check with her as soon as I can about where they ended up, but the good news is that they are done.
